### ISSUE TITLE
No database tables created

### ISSUE THREAD

**Issue by mkrokos** [userexec/Sendy-Invoicing#2]
Hello, I installed Sendy Invoicing and built successfully. Additions were indeed made to all three files.

The problem is that when I tick the checkbox for invoice creation for a brand, it won't stay ticked. And then I realised that no changes were made in the database. There is no 'security_tokens' table and no 'invoice' table is 'apps'

Am I missing something or is this an issue?

**Comment by userexec** [comment]
Could be an issue in a new version. I'll run through a local install in a bit here and see what's up.

**Comment by userexec** [comment]
How embarrassing lol. Missing comma on line 18 of config.php. Just pop the comma on there after the API key string and it should go ahead and create the database tables and column next time you click the invoicing checkbox. Repo updated, and thanks for giving me a heads up that it wasn't working!

**Comment by mkrokos** [comment]
Yes, that worked like a charm. Nevertheless, another issue arised now that I can't figure out because it doesn't happen every time. When I (as an admin) try to edit a brand, ticking/unticking the "Charge via Invoice" checkbox only changes state momentarily. And then it jumps back to previous state. 

Also, another thing is that in the "invoicing.php" and the "invoicing-preview.php" files, you have the currency hardcoded to USD ($). Wouldn't it be better to pull the stored currency for the brand?
(sorry for mentioning this under the same issue)
